"""Agent API — RESTful endpoints for programmatic access by ClaudeBot, OpenClaw, etc.

All endpoints are under /api/v1/agent/ and require Bearer token auth via the
agent_api_key setting (generated by agent-setup.sh --api-key).

Response envelope:
    { "ok": true, "data": { ... } }
    { "ok": false, "error": "message", "code": "ERROR_CODE" }
"""

import json
import functools
from datetime import datetime
from flask import Blueprint, request, jsonify

from backend.db import (
    get_all_devices, get_device, set_nickname,
    get_scan_history, get_vulns_for_scan,
    get_intrusion_attempts, get_intrusion_count, get_intrusion_stats,
    get_setting, set_setting, get_device_tags, set_device_tags,
    get_devices_with_tag, get_new_devices,
)
from backend.scanner import get_default_interface, get_network_stats

agent_bp = Blueprint('agent_api', __name__, url_prefix='/api/v1/agent')


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

def require_api_key(f):
    """Decorator that validates the Bearer token against stored agent_api_key."""
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        api_key = get_setting('agent_api_key')
        if not api_key:
            return _err('Agent API key not configured. Run: ./agent-setup.sh --api-key', 'NO_API_KEY', 503)

        auth = request.headers.get('Authorization', '')
        token = None
        if auth.startswith('Bearer '):
            token = auth[7:]
        elif request.args.get('api_key'):
            token = request.args.get('api_key')

        if not token or token != api_key:
            return _err('Invalid or missing API key', 'UNAUTHORIZED', 401)

        return f(*args, **kwargs)
    return wrapper


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ok(data=None):
    return jsonify({'ok': True, 'data': data or {}}), 200


def _err(message, code='ERROR', status=400):
    return jsonify({'ok': False, 'error': message, 'code': code}), status


def _parse_device(d):
    """Normalize a device dict for API output."""
    if isinstance(d.get('tags'), str):
        try:
            d['tags'] = json.loads(d['tags'])
        except (json.JSONDecodeError, TypeError):
            d['tags'] = []
    elif not d.get('tags'):
        d['tags'] = []
    return d


# ---------------------------------------------------------------------------
# System / Status
# ---------------------------------------------------------------------------

@agent_bp.route('/status', methods=['GET'])
@require_api_key
def agent_status():
    """System status, network info, and service health.

    GET /api/v1/agent/status
    Response: {ok, data: {network, device_count, intrusion_stats, auto_scan_policy, uptime}}
    """
    iface, subnet, gateway = get_default_interface()
    devices = get_all_devices()
    i_stats = get_intrusion_stats()
    policy = get_setting('auto_scan_policy', 'scanners')

    return _ok({
        'network': {
            'interface': iface,
            'subnet': subnet,
            'gateway': gateway,
        },
        'device_count': len(devices),
        'intrusion_stats': {
            'total_attempts': i_stats.get('total_attempts', 0),
            'last_attempt': dict(i_stats['last_attempt']) if i_stats.get('last_attempt') else None,
        },
        'auto_scan_policy': policy,
        'timestamp': datetime.now().isoformat(),
    })


# ---------------------------------------------------------------------------
# Devices
# ---------------------------------------------------------------------------

@agent_bp.route('/devices', methods=['GET'])
@require_api_key
def agent_devices():
    """List all discovered devices.

    GET /api/v1/agent/devices
    Query params:
        type=<device_type>     Filter by type (router, computer, phone, etc.)
        tag=<tag>              Filter by tag
        new=1                  Only devices seen in the last hour
    Response: {ok, data: {devices: [...], count: N}}
    """
    devices = get_all_devices()
    devices = [_parse_device(d) for d in devices]

    # Filters
    dtype = request.args.get('type')
    if dtype:
        devices = [d for d in devices if d.get('device_type') == dtype]

    tag = request.args.get('tag')
    if tag:
        devices = [d for d in devices if tag in (d.get('tags') or [])]

    if request.args.get('new') == '1':
        now = datetime.now()
        filtered = []
        for d in devices:
            if d.get('first_seen'):
                try:
                    first = datetime.fromisoformat(d['first_seen'])
                    if (now - first).total_seconds() <= 3600:
                        filtered.append(d)
                except (ValueError, TypeError):
                    pass
        devices = filtered

    return _ok({'devices': devices, 'count': len(devices)})


@agent_bp.route('/devices/<mac>', methods=['GET'])
@require_api_key
def agent_device_detail(mac):
    """Get a single device by MAC address.

    GET /api/v1/agent/devices/<mac>
    Response: {ok, data: {device: {...}, scan_history: [...], tags: [...]}}
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    device = _parse_device(device)
    scans = get_scan_history(mac)
    for s in scans:
        s['results'] = json.loads(s['results']) if isinstance(s['results'], str) else s['results']
        s['vulns'] = get_vulns_for_scan(s['id'])

    return _ok({
        'device': device,
        'scan_history': scans,
        'tags': device.get('tags', []),
    })


@agent_bp.route('/devices/<mac>/nickname', methods=['PUT'])
@require_api_key
def agent_set_nickname(mac):
    """Set a device nickname.

    PUT /api/v1/agent/devices/<mac>/nickname
    Body: {"nickname": "My Router"}
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    data = request.get_json(silent=True) or {}
    nickname = data.get('nickname', '')
    set_nickname(mac, nickname)
    return _ok({'mac': mac, 'nickname': nickname})


@agent_bp.route('/devices/<mac>/tags', methods=['GET'])
@require_api_key
def agent_get_tags(mac):
    """Get tags for a device.

    GET /api/v1/agent/devices/<mac>/tags
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    tags = get_device_tags(mac)
    return _ok({'mac': mac, 'tags': tags})


@agent_bp.route('/devices/<mac>/tags', methods=['PUT'])
@require_api_key
def agent_set_tags(mac):
    """Replace all tags for a device.

    PUT /api/v1/agent/devices/<mac>/tags
    Body: {"tags": ["auto-scan", "critical"]}
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    data = request.get_json(silent=True) or {}
    tags = data.get('tags', [])
    if not isinstance(tags, list):
        return _err('tags must be a list', 'INVALID_INPUT')
    set_device_tags(mac, tags)
    return _ok({'mac': mac, 'tags': tags})


@agent_bp.route('/devices/<mac>/tags', methods=['POST'])
@require_api_key
def agent_add_tag(mac):
    """Add a tag to a device (idempotent).

    POST /api/v1/agent/devices/<mac>/tags
    Body: {"tag": "auto-scan"}
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    data = request.get_json(silent=True) or {}
    tag = data.get('tag', '')
    if not tag:
        return _err('tag is required', 'INVALID_INPUT')

    tags = get_device_tags(mac)
    if tag not in tags:
        tags.append(tag)
        set_device_tags(mac, tags)
    return _ok({'mac': mac, 'tags': tags})


@agent_bp.route('/devices/<mac>/tags/<tag>', methods=['DELETE'])
@require_api_key
def agent_remove_tag(mac, tag):
    """Remove a tag from a device.

    DELETE /api/v1/agent/devices/<mac>/tags/<tag>
    """
    device = get_device(mac)
    if not device:
        return _err(f'Device not found: {mac}', 'NOT_FOUND', 404)

    tags = get_device_tags(mac)
    if tag in tags:
        tags.remove(tag)
        set_device_tags(mac, tags)
    return _ok({'mac': mac, 'tags': tags})


# ---------------------------------------------------------------------------
# Scanning
# ---------------------------------------------------------------------------

@agent_bp.route('/scan/discover', methods=['POST'])
@require_api_key
def agent_discover():
    """Trigger a network discovery scan (ARP + nmap ping).

    POST /api/v1/agent/scan/discover
    Response: {ok, data: {count: N, devices: [...]}}

    Note: This is synchronous and may take 10-30 seconds.
    """
    from backend.scanner import arp_scan, nmap_discovery

    devices = arp_scan()
    try:
        nmap_devices = nmap_discovery()
        dev_by_mac = {d['mac']: d for d in devices}
        for nd in nmap_devices:
            if nd['mac'] in dev_by_mac:
                existing = dev_by_mac[nd['mac']]
                if nd.get('vendor') and not existing.get('vendor'):
                    existing['vendor'] = nd['vendor']
                if nd.get('hostname') and not existing.get('hostname'):
                    existing['hostname'] = nd['hostname']
            else:
                devices.append(nd)
    except Exception:
        pass

    return _ok({'count': len(devices), 'devices': devices})


@agent_bp.route('/scan/port', methods=['POST'])
@require_api_key
def agent_port_scan():
    """Trigger a port scan on a device. Runs synchronously and returns results.

    POST /api/v1/agent/scan/port
    Body: {"ip": "192.168.1.100", "mac": "aa:bb:cc:dd:ee:ff"}
    Response: {ok, data: {ports: [...], os: "...", vulnerabilities: [...]}}

    Note: This is synchronous and may take 1-5 minutes.
    """
    from backend.scanner import stealth_port_scan

    data = request.get_json(silent=True) or {}
    ip = data.get('ip')
    mac = data.get('mac')
    if not ip or not mac:
        return _err('ip and mac are required', 'INVALID_INPUT')

    results = stealth_port_scan(ip, mac)
    if 'error' in results:
        return _err(results['error'], 'SCAN_FAILED')

    return _ok(results)


# ---------------------------------------------------------------------------
# Intrusions
# ---------------------------------------------------------------------------

@agent_bp.route('/intrusions', methods=['GET'])
@require_api_key
def agent_intrusions():
    """Get intrusion attempt log with pagination.

    GET /api/v1/agent/intrusions?limit=50&offset=0
    Response: {ok, data: {attempts: [...], total: N, limit: N, offset: N}}
    """
    limit = request.args.get('limit', 50, type=int)
    offset = request.args.get('offset', 0, type=int)
    limit = min(limit, 500)  # cap

    attempts = get_intrusion_attempts(limit=limit, offset=offset)
    total = get_intrusion_count()

    return _ok({
        'attempts': attempts,
        'total': total,
        'limit': limit,
        'offset': offset,
    })


@agent_bp.route('/intrusions/active', methods=['GET'])
@require_api_key
def agent_active_intrusions():
    """Get currently active intrusion scans.

    GET /api/v1/agent/intrusions/active
    Response: {ok, data: {active_scans: [...], count: N}}
    """
    # Import here to avoid circular imports — the detector instance is on app
    from flask import current_app
    # Access the intrusion detector via the app context
    # We'll register it during blueprint init
    detector = current_app.config.get('INTRUSION_DETECTOR')
    if detector:
        active = detector.get_active_scans()
        scans = list(active.values())
    else:
        scans = []

    return _ok({'active_scans': scans, 'count': len(scans)})


@agent_bp.route('/intrusions/stats', methods=['GET'])
@require_api_key
def agent_intrusion_stats():
    """Get intrusion statistics summary.

    GET /api/v1/agent/intrusions/stats
    Response: {ok, data: {total_attempts, last_attempt, ...}}
    """
    stats = get_intrusion_stats()
    total = get_intrusion_count()
    stats['total_attempts'] = total
    return _ok(stats)


# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

@agent_bp.route('/network', methods=['GET'])
@require_api_key
def agent_network():
    """Get network configuration and interface statistics.

    GET /api/v1/agent/network
    Response: {ok, data: {interface, subnet, gateway, stats: {...}}}
    """
    iface, subnet, gateway = get_default_interface()
    stats = get_network_stats()

    return _ok({
        'interface': iface,
        'subnet': subnet,
        'gateway': gateway,
        'interface_stats': stats,
    })


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------

@agent_bp.route('/settings', methods=['GET'])
@require_api_key
def agent_get_settings():
    """Get all agent-relevant settings.

    GET /api/v1/agent/settings
    Response: {ok, data: {auto_scan_policy: "scanners"}}
    """
    return _ok({
        'auto_scan_policy': get_setting('auto_scan_policy', 'scanners'),
    })


@agent_bp.route('/settings', methods=['PUT'])
@require_api_key
def agent_set_settings():
    """Update settings.

    PUT /api/v1/agent/settings
    Body: {"auto_scan_policy": "all"}
    Accepted keys: auto_scan_policy (all|new|scanners|tagged|none)
    """
    data = request.get_json(silent=True) or {}

    if 'auto_scan_policy' in data:
        policy = data['auto_scan_policy']
        valid = ['all', 'new', 'scanners', 'tagged', 'none']
        if policy not in valid:
            return _err(f'auto_scan_policy must be one of: {", ".join(valid)}', 'INVALID_INPUT')
        set_setting('auto_scan_policy', policy)

    return _ok({
        'auto_scan_policy': get_setting('auto_scan_policy', 'scanners'),
    })


# ---------------------------------------------------------------------------
# Vulnerabilities
# ---------------------------------------------------------------------------

@agent_bp.route('/vulnerabilities', methods=['GET'])
@require_api_key
def agent_vulnerabilities():
    """Get all vulnerabilities across all devices, sorted by severity.

    GET /api/v1/agent/vulnerabilities?severity=CRITICAL&limit=100
    Response: {ok, data: {vulnerabilities: [...], count: N}}
    """
    severity_filter = request.args.get('severity', '').upper()
    limit = request.args.get('limit', 100, type=int)

    devices = get_all_devices()
    all_vulns = []

    for device in devices:
        mac = device['mac']
        scans = get_scan_history(mac)
        if not scans:
            continue
        # Only latest scan per device
        latest = scans[0]
        results = json.loads(latest['results']) if isinstance(latest['results'], str) else latest['results']
        vulns = get_vulns_for_scan(latest['id'])

        for v in vulns:
            v['device_mac'] = mac
            v['device_ip'] = device.get('ip', '')
            v['device_name'] = device.get('nickname') or device.get('hostname') or device.get('ip', '')
            v['scan_time'] = latest.get('scan_time', '')
            all_vulns.append(v)

    # Filter by severity
    if severity_filter:
        all_vulns = [v for v in all_vulns if v.get('severity', '').upper() == severity_filter]

    # Sort by severity priority
    sev_order = {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3}
    all_vulns.sort(key=lambda v: sev_order.get(v.get('severity', '').upper(), 99))

    all_vulns = all_vulns[:limit]

    return _ok({'vulnerabilities': all_vulns, 'count': len(all_vulns)})


# ---------------------------------------------------------------------------
# Bulk operations
# ---------------------------------------------------------------------------

@agent_bp.route('/bulk/tag', methods=['POST'])
@require_api_key
def agent_bulk_tag():
    """Add a tag to multiple devices at once.

    POST /api/v1/agent/bulk/tag
    Body: {"macs": ["aa:bb:...", "cc:dd:..."], "tag": "critical"}
    Response: {ok, data: {updated: N}}
    """
    data = request.get_json(silent=True) or {}
    macs = data.get('macs', [])
    tag = data.get('tag', '')

    if not macs or not tag:
        return _err('macs (list) and tag (string) are required', 'INVALID_INPUT')

    updated = 0
    for mac in macs:
        device = get_device(mac)
        if not device:
            continue
        tags = get_device_tags(mac)
        if tag not in tags:
            tags.append(tag)
            set_device_tags(mac, tags)
        updated += 1

    return _ok({'updated': updated, 'tag': tag})


@agent_bp.route('/bulk/scan', methods=['POST'])
@require_api_key
def agent_bulk_scan():
    """Trigger port scans on multiple devices. Returns a summary.

    POST /api/v1/agent/bulk/scan
    Body: {"macs": ["aa:bb:...", "cc:dd:..."]}

    Note: Scans run synchronously in sequence. This endpoint may take many minutes.
    For async scanning, use /scan/port for individual devices.
    Response: {ok, data: {results: [{mac, ip, ports_found, vulns_found}, ...], count: N}}
    """
    from backend.scanner import stealth_port_scan

    data = request.get_json(silent=True) or {}
    macs = data.get('macs', [])

    if not macs:
        return _err('macs list is required', 'INVALID_INPUT')

    results = []
    for mac in macs:
        device = get_device(mac)
        if not device:
            results.append({'mac': mac, 'error': 'not found'})
            continue

        ip = device.get('ip')
        if not ip:
            results.append({'mac': mac, 'error': 'no IP'})
            continue

        scan = stealth_port_scan(ip, mac)
        ports_found = len(scan.get('ports', []))
        vulns_found = sum(len(p.get('vulns', [])) for p in scan.get('ports', []))

        results.append({
            'mac': mac,
            'ip': ip,
            'ports_found': ports_found,
            'vulns_found': vulns_found,
            'os': scan.get('os', ''),
            'scan_id': scan.get('scan_id'),
        })

    return _ok({'results': results, 'count': len(results)})
